/*
 * ICS4U Summative
 * Course Planner
 * Agenda
 */
package CourseAgenda;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Tuna
 */
public class Overview extends javax.swing.JFrame {
    
    // List of course averages
    ArrayList<Double> averageList = new ArrayList<>();

    /**
     * Creates new form Overview
     */
    public Overview() {
        initComponents();
        writeRows();
        displayOverallAverage();
        displayNumberOfItems();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        overviewTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        overallAverageLabel = new javax.swing.JLabel();
        numberOfItemLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 255));
        setForeground(java.awt.Color.black);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Overview");

        overviewTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Course", "Average"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(overviewTable);

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Overall Average :");

        overallAverageLabel.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        overallAverageLabel.setForeground(new java.awt.Color(255, 255, 255));
        overallAverageLabel.setText("jLabel3");

        numberOfItemLabel.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        numberOfItemLabel.setForeground(new java.awt.Color(255, 255, 255));
        numberOfItemLabel.setText("You have ? ungraded item on your agenda.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(391, 391, 391)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 1, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numberOfItemLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(overallAverageLabel)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(overallAverageLabel))
                .addGap(18, 18, 18)
                .addComponent(numberOfItemLabel)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    // Create a new row on the table with as new course and its average
    private void writeRows() {
        // Changes background to blue
        getContentPane().setBackground(new java.awt.Color(0,153,255));
        ArrayList<String> courseList = Course.getCourseList();
       
        // Go through each course
        for(String newCourseName: courseList){
            Course courseName = new Course(newCourseName);
            
            // Put course name and average to the table
            Object overviewItem[] = new Object[2];
            overviewItem[0] = newCourseName;
            String average = String.format("%.2f", courseName.getAverage());
            
            //Replaces the NaN with No Grade Available for client 
            if(average.equals("NaN")){
                average = "No Grade Available !";
            } else {
                averageList.add(Double.parseDouble(average));
            }
            overviewItem[1] = average;
            DefaultTableModel table = (DefaultTableModel)overviewTable.getModel();
            table.addRow(overviewItem);
        }
    }
    
    // Displays the overall average on the overview page
    private void displayOverallAverage(){
        double sum = 0;
        for (double temp : averageList) {
            sum += temp;
	}
        double overallAverage = sum/averageList.size();
        
        //Round the average and display it on the screen
        overallAverageLabel.setText(String.format("%.2f", overallAverage));
    }
    
    //Displays the number of ungraded items on the agenda
    private void displayNumberOfItems(){
        int numberOfItem = 0;
        for(String data:Course.fileLines){
            String[] values = data.split(",");
            try{
                System.out.println(values[3]);
            }catch (ArrayIndexOutOfBoundsException a){
                numberOfItem +=1;
            }  
        }  
        // Sets the label to display number of ungraded items
        numberOfItemLabel.setText("You have " + Integer.toString(numberOfItem) + " ungraded items on you list.");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Overview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Overview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Overview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Overview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Overview().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel numberOfItemLabel;
    private javax.swing.JLabel overallAverageLabel;
    private javax.swing.JTable overviewTable;
    // End of variables declaration//GEN-END:variables
}
